# Generated by Django 3.1.5 on 2021-02-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(null=True, to='books.Books'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_wishlist', to='books.wishlist'),
        ),
    ]
