# Generated by Django 3.1.6 on 2021-02-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210202_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='books',
            name='description',
        ),
        migrations.RemoveField(
            model_name='books',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='books',
            name='sub_title',
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(to='books.Books'),
        ),
    ]
